spring.application.name=WalletAPI
server.port=8082

logging.level.root=INFO
logging.level.com.sfl.walletapi=DEBUG

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{40} - %msg%n

spring.datasource.url=jdbc:h2:file:./data/walletsdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console